name: Build using CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download CPU Torch
      run: curl https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.1%2Bcpu.zip --output libtorch.zip && unzip libtorch.zip ~/libtorch/share/cmake/Torch

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make
