name: Lint using Clang format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: ERROR=$(find . \( -iname '*.hpp' -o -iname '*.cpp' \) | xargs clang-format -style=Microsoft --dry-run)
        if [ -n "$ERROR" ]; then
          echo "Linting dryrun failed..."
          exit 1
        else
          echo "Linting dryrun successful!"
          exit 0
        fi
