name: Lint using Clang format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: |
        set -o pipefail
        find . \( -iname '*.hpp' -o -iname '*.cpp' \) | xargs clang-format -style=Microsoft --dry-run -Werror
